### PR TITLE
Add an irl example for linear system

### LINKED ISSUE #21: Implement an IRL algorithm (linear system)
@hnlee77 reference 달아주세요~

### PR DESCRIPTION
**Pull request by hnlee77**
Resolved #21 .

## Summary
An integral reinforcement learning (IRL) algorithm is implemented for linear system.
It converged to ARE solution for the linear system.
The optimal solution is as follows.
```P = [0.05, 0.0039; 0.0039, 0.2085]```

### Online training progress
```'
julia> main()
(i, irl.V̂.param) = (1, [0.027534938824213172; 0.0010557258018106597; 0.03697905703706195])
(i, irl.V̂.param) = (2, [0.03990498086766991; 0.002859794454445496; 0.06816645090159196])
(i, irl.V̂.param) = (3, [0.045462828016241214; 0.004470547607978162; 0.09422455297243854])
(i, irl.V̂.param) = (4, [0.04795970519996298; 0.005669018192464714; 0.11581524522848588])
(i, irl.V̂.param) = (5, [0.04908126040655958; 0.006484962654713332; 0.13357600401253636])
(i, irl.V̂.param) = (6, [0.04958494009055353; 0.007010875562407924; 0.14809823156885152])
(i, irl.V̂.param) = (7, [0.049811076961281536; 0.0073365107023041385; 0.15991341040601684])
(i, irl.V̂.param) = (8, [0.04991256397028329; 0.007531238914799822; 0.16948711343295808])
(i, irl.V̂.param) = (9, [0.049958117185159995; 0.00764355767235331; 0.17721902932017022])
(i, irl.V̂.param) = (10, [0.04997856967723194; 0.0077055221840715005; 0.1834468947413743])
(i, irl.V̂.param) = (11, [0.04998762487455023; 0.007737581225173821; 0.18845257614190322])
(i, irl.V̂.param) = (12, [0.0499910645894288; 0.007752499311062805; 0.19246903048328817])
(i, irl.V̂.param) = (13, [0.04999402060894557; 0.007757289074844241; 0.19568738244283446])
(i, irl.V̂.param) = (14, [0.049999201265624085; 0.007756082412643141; 0.1982634465507848])
(i, irl.V̂.param) = (15, [0.04999049527990376; 0.007756121495715194; 0.2003233151965548])
(i, irl.V̂.param) = (16, [0.0500176820646422; 0.007745155480193123; 0.2019701320457739])
(i, irl.V̂.param) = (17, [0.049865260231190624; 0.007783837302566654; 0.203282113593424])
(i, irl.V̂.param) = (18, [0.04984836290673218; 0.007785076607946407; 0.20433157108922168])
(i, irl.V̂.param) = (19, [0.050243351112691334; 0.0076721086209329365; 0.20517702887312886])
stop_conds_dict = Dict{Symbol, Bool}(:w_tol => 1)
P = [0.050243351112691334 0.0038360543104664683; 0.0038360543104664683 0.20517702887312886]
```

### Simulation results
image

## Todo
- Move training progress (callback function: ```affect!``` ) to the IRL algorithm.

### CODE REVIEW

**Comment by JinraeKim** [comment]
@hnlee77 
From the next PR,
please assign appropriate values for the assignee, linked issue, project, etc.
Also, convert PRs to "draft" if it's not yet ready to be merged (and it seems so as you leave a to-do list).

**Comment by JinraeKim** [comment]
@hnlee77 
Can you provide "an exact optimal solution" to the given linear system for comparison?

**Comment by hnlee77** [comment]
> @hnlee77
> Can you provide "an exact optimal solution" to the given linear system for comparison?

I updated the [previous comment](https://github.com/JinraeKim/FlightSims.jl/pull/43#issue-662965372).

**Comment by JinraeKim** [comment]
Checked with @hnlee77 personally.

**Pull request merged**
